name: CI Pipeline  

on:  
  push:  
    branches:  
      - main  
      - '**'  # Runs on all branches  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Set up JDK 17  
        uses: actions/setup-java@v3  
        with:  
          distribution: 'temurin'  
          java-version: '17'  

      - name: Install Chrome  
        run: |  
          sudo apt update  
          sudo apt install -y google-chrome-stable  

      - name: Get Chrome version  
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
         CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
         && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
         && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
         && cd /tmp \
         && unzip chromedriver_linux64.zip \
         && rm -rf chromedriver_linux64.zip \
         && sudo mv chromedriver /usr/local/bin/chromedriver \
         && sudo chmod +x /usr/local/bin/chromedriver \
         && chromedriver --version

      - name: Grant execute permission to Gradle Wrapper  
        run: chmod +x SelXpro/gradlew  

      - name: Compile with Gradle  
        run: |  
          cd SelXpro  
          ./gradlew compileJava  

      - name: Run Tests  
        run: |  
          cd SelXpro  
          ./gradlew clean --info test -PincludeGroupNames="smoke" -PexcludeGroupNames="bug"

      - name: Archive Test Reports  
        uses: actions/upload-artifact@v4  
        with:  
          name: test-report  
          path: SelXpro/Reports/
